version: '3.1'
volumes:
        postgres-data:
services:
        db:
                image: postgres:alpine
                restart: always
                volumes:
                  - ./postgres-data:/var/lib/postgresql/data
                environment:
                  POSTGRES_PASSWORD: p4ssword_
        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080
        rpgbot:
          build: .
          container_name: "rpgbot"
          volumes:
            - ./config.json:/config.json
          links:
            - db
          environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: p4ssword_
